# El modulo numpy

In [35]:
# Carguemos el modulo numpy
import numpy as np


In [ ]:
# Documentacion del modulo numpy
help(np)

In [ ]:
# Documentacion del submodulo random
help(np.random)

In [ ]:
# Documentacion del submodulo linalg
help(np.linalg)

In [ ]:
# Documentacion de fft
help(np.fft)

In [ ]:
# Documentacion de polynomial
help(np.polynomial)

In [7]:
# Elementos que componen al submodulo random
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [ ]:
# # Elementos / funciones de interes del submodulo random
#  'beta',
#  'binomial',
#  'bit_generator',
#  'bytes',
#  'chisquare',
#  'choice',
#  'default_rng',
#  'dirichlet',
#  'exponential',
#  'f',
#  'gamma',
#  'geometric',
#  'get_bit_generator',
#  'get_state',
#  'gumbel',
#  'hypergeometric',
#  'laplace',
#  'logistic',
#  'lognormal',
#  'logseries',
#  'mtrand',
#  'multinomial',
#  'multivariate_normal',
#  'negative_binomial',
#  'noncentral_chisquare',
#  'noncentral_f',
#  'normal',
#  'pareto',
#  'permutation',
#  'poisson',
#  'power',
#  'rand',
#  'randint',
#  'randn',
#  'random',
#  'random_integers',
#  'random_sample',
#  'ranf',
#  'rayleigh',
#  'sample',
#  'seed',
#  'set_bit_generator',
#  'set_state',
#  'shuffle',
#  'standard_cauchy',
#  'standard_exponential',
#  'standard_gamma',
#  'standard_normal',
#  'standard_t',
#  'test',
#  'triangular',
#  'uniform',
#  'vonmises',
#  'wald',
#  'weibull',
#  'zipf'

In [8]:
# Documentacion de la funcion triangular (submodulo random)
help(np.random.triangular)

Help on built-in function triangular:

triangular(...) method of numpy.random.mtrand.RandomState instance
    triangular(left, mode, right, size=None)
    
    Draw samples from the triangular distribution over the
    interval ``[left, right]``.
    
    The triangular distribution is a continuous probability
    distribution with lower limit left, peak at mode, and upper
    limit right. Unlike the other distributions, these parameters
    directly define the shape of the pdf.
    
    .. note::
        New code should use the `~numpy.random.Generator.triangular`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    left : float or array_like of floats
        Lower limit.
    mode : float or array_like of floats
        The value where the peak of the distribution occurs.
        The value must fulfill the condition ``left <= mode <= right``.
    right : float or array_like of floats
 

# Primeros pasos con numpy

In [11]:
# Lista
l1 = [12,45,234,2543,45]
l1

[12, 45, 234, 2543, 45]

In [13]:
# Sumemos 0.5 a cada elemento de l1

l1_mas_05 = []

for elemento in l1:
  print(elemento + 0.5)
  l1_mas_05.append(elemento + 0.5)

l1_mas_05

12.5
45.5
234.5
2543.5
45.5


[12.5, 45.5, 234.5, 2543.5, 45.5]

In [14]:
# A partir de un dato de tipo lista construyamos un objeto propio de numpy
vec1 = np.array(l1)
vec1

array([  12,   45,  234, 2543,   45])

In [15]:
# Operaciones son vectorizadas
vec1 + 0.5

array([  12.5,   45.5,  234.5, 2543.5,   45.5])

In [17]:
vec2 = vec1 ** (3.14159)
vec2

array([2.45665975e+03, 1.56212543e+05, 2.77398971e+07, 4.99116666e+10,
       1.56212543e+05])

In [18]:
# Tipo de dato
type(vec1)

numpy.ndarray

In [ ]:
# Documentacion de la funcion randint del submodulom random
help(np.random.randint)

In [21]:
# Generemos 10000 elementos en [0,20]
notas1 = np.random.randint(0,21,10**4)
notas1

array([ 4, 20,  0, ..., 15, 15, 17])

In [22]:
# Funcion len
len(notas1)

10000

In [25]:
# Iterable
notas1[:10]

array([ 4, 20,  0,  4, 11,  2,  4,  8, 16,  5])

In [26]:
# Lista de metodos que se puede aplicar a un dato de tipo numpy.ndarray
dir(vec1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [ ]:
# # Metodos de interes para un dato de tipo numpy.ndarray
#  'all',
#  'any',
#  'argmax',
#  'argmin',
#  'argpartition',
#  'argsort',
#  'astype',
#  'base',
#  'byteswap',
#  'choose',
#  'clip',
#  'compress',
#  'conj',
#  'conjugate',
#  'copy',
#  'ctypes',
#  'cumprod',
#  'cumsum',
#  'data',
#  'diagonal',
#  'dot',
#  'dtype',
#  'dump',
#  'dumps',
#  'fill',
#  'flags',
#  'flat',
#  'flatten',
#  'getfield',
#  'imag',
#  'item',
#  'itemset',
#  'itemsize',
#  'max',
#  'mean',
#  'min',
#  'nbytes',
#  'ndim',
#  'newbyteorder',
#  'nonzero',
#  'partition',
#  'prod',
#  'ptp',
#  'put',
#  'ravel',
#  'real',
#  'repeat',
#  'reshape',
#  'resize',
#  'round',
#  'searchsorted',
#  'setfield',
#  'setflags',
#  'shape',
#  'size',
#  'sort',
#  'squeeze',
#  'std',
#  'strides',
#  'sum',
#  'swapaxes',
#  'take',
#  'tobytes',
#  'tofile',
#  'tolist',
#  'tostring',
#  'trace',
#  'transpose',
#  'var',
#  'view'

In [ ]:
# Diferencias entre atributos (propiedades) y metodos
  # Atributos/propiedad no requieres parentesis
  # metodos si requiere parentesis



In [ ]:
# Documentacion de shape
help(vec2.shape)

In [ ]:
# Documentacion de mean
help(vec2.mean)

In [32]:
#
notas1.shape

(10000,)

In [33]:
#
notas1.mean()

10.0167

In [34]:
# Generemos 20000 de estos vectores con 10000 notas en [0,20]
# Almacenemos los promedios aritmeticos de estos 20000 vectores

# Guardemos en una lista los 20000 promedios aritmeticos
lista_medias = []

for i in range(20000):
  lista_medias.append(np.random.randint(0,21,10000).mean())

# Calculemos el promedio aritmetico de esos 20000 promedios aritmeticos
np.array(lista_medias).mean()

9.999938600000002

In [ ]:
# Calculemos la determinante de una matriz
help(np.linalg.det)

In [52]:
# Generemos una matriz de 1000x1000 de numeros aleatorios
mat1 = np.random.randint(0,5, (10**2, 10**2))

# Calculemos la determinante
np.linalg.det(mat1)

-3.473755931292726e+94

In [ ]:
# Autovalores /Autovectores
help(np.linalg.eigvals)

In [58]:
# Calculemos los autovalores de mat1
autovalores = np.linalg.eigvals(mat1)
autovalores.shape

(100,)

In [68]:
# Lista con autovalores reales
eig_real = []
# Separemos los autovalores reales
for autovalor in autovalores:
  if autovalor.imag == 0.0:
    eig_real.append(autovalor)

eig_real



[(199.3350629771754+0j),
 (12.651982855873488+0j),
 (9.345237717936355+0j),
 (8.844893192693352+0j),
 (5.7234325545016755+0j),
 (-6.0611646715460585+0j)]

In [ ]:
# De los autovalores complejos, obtener los 10 de mayor norma

In [ ]:
# De los autovalores complejos, obtener aquello cuya parte real sea mayor que 200